title: UVA CS 2130 Student Notes
description: Notes from CSO 1 with DGraham, Spring 2024
theme: just-the-docs

url: https://ameimeilia.github.io

baseurl: "/cso1-notes"

nav_enabled: true

math: katex